### ISSUE TITLE
A handful of issues

### ISSUE THREAD

**Issue by Phil1216** [aws-samples/websocket-chat-application#27]
Environment:
Windows
node 16.13.2
npm 8.1.2

When I cloned the repo I ran into a few issues.
1. The same as #26. I left a comment there for how I fixed it.

2. Typescript was complaining about missing imports involving @aws-cdk/aws-apigatewayv2-alpha, which is imported by a couple of the stack files under infrastructure/lib so I had to add ```"@aws-cdk/aws-apigatewayv2-alpha": "^2.29.1-alpha.0"``` to infrastructure/package.json in order to fix it. It's either a missing import or something peculiar with lockfiles (I recall that my node detected that the lockfile was for a previous version of npm and automatically made changes). 

3. I also had to change the cognitoDomainPrefix string inside infrastructure/bin/serverless-chat.ts (line 69) because it was saying that serverless-chat-users prefix was unavailable. I took a glance at the [Cognito developer guide](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-assign-domain-prefix.html) and the wording there suggests that these prefixes need to be unique.

**Comment by santatamas** [comment]
Hi Phil, 

thanks for this! I fixed the file references, added the missing package and also removed the preset cognito domain prefix value. I extended the readme to call out that you need to declare a globally unique domain prefix before deployment.

On the frontend side, I updated the Angular version to 15.

Let me know if this solves your issues!

Kind regards,
Tamas
