### ISSUE TITLE
GetChannelMessages Handler

### ISSUE THREAD

**Issue by Phil1216** [aws-samples/websocket-chat-application#28]
I found an issue with the GetChannelMessages lambda handler. Apparently, if the channel name contains a space, messages don't show up for the client.

The problem, I believe, is that urls have to escape spaces with a %20. Here is a portion of the event from cloudwatch:
```
{\"resource\":\"/api/channels/{id}/messages\",\"path\":\"/api/channels/Throwing%20Down/messages\"
```
```
"pathParameters\":{\"id\":\"Throwing%20Down\"}
```
I think what happens is that the handler queries dynamodb for "Throwing%20Down" instead of "Throwing Down", which causes it to return an empty list.

**Comment by santatamas** [comment]
Thanks for reporting this! I'll look into it :)

**Comment by santatamas** [comment]
Fixed in latest :)
