### ISSUE TITLE
Issue with reopening Websocket after Idle 10m

### ISSUE THREAD

**Issue by Amerieum** [aws-samples/websocket-chat-application#31]
There is non need for this line in **websocket.service.ts** as it also prevent the Observable from subscribing again which means the websocket is reopened but the frontend does not process it no more, there might be a better way of doing this but removing this line worked fine, 
    observer.complete();
	
I am no Angular expert, but removing this line worked fine in my deployment here

https://eu-west-3-amer-demo.auth.eu-west-3.amazoncognito.com/login?client_id=3uouf490c5u4mfej54igv25am9&response_type=token&redirect_uri=https://d17sdmhwxn0gs2.cloudfront.net/callback

On another note, there seems to be an issue with the way https://github.com/pladaria/reconnecting-websocket  is used in reconnecting-websocket  and in principle allows for reconnecting a closed socket with the option startClosed which defaults to false and even changing it to true does nothing , the only thing that worked was removing observer.complete(); from **websocket.service.ts** 

To simulate idle timeout , I do not wait 10 minutes I just remove the connection from the API Gateway Websocket which is detected as websocket closed in the frontend 

Example :

aws  apigatewaymanagementapi delete-connection --endpoint-url https://***********.execute-api.eu-west-3.amazonaws.com/wss --connection-id CmGXUcpYiGYCGBA=

**Comment by santatamas** [comment]
Hi! Thanks a lot for reporting this. Would you be able to create a pull request? I'll be happy to merge.

Cheers,
Tamas

**Comment by Amerieum** [comment]
Hi!
Thanks !
Done 

Cheers,
Amer

**Comment by santatamas** [comment]
Thank you for your contribution, it's really appreciated! I merged the PR :)
