### ISSUE TITLE
Project needs to be migrated to CDK v2

### ISSUE THREAD

**Issue by popovitsj** [aws-samples/websocket-chat-application#42]
During npm install, we get a bunch of warnings about CDK v1 having reached end of life, eg.:

```
npm WARN deprecated @aws-cdk/cloud-assembly-schema@1.204.0: AWS CDK v1 has reached End-of-Support on 2023-06-01.
npm WARN deprecated This package is no longer being updated, and users should migrate to AWS CDK v2.
```

Can we migrate to CDK v2?

**Comment by santatamas** [comment]
I removed the unused dependencies, you shouldn't get any warnings anymore :) Thanks for reporting!
