### ISSUE TITLE
failed to complie client UI app: missing websocket-auth-event models

### ISSUE THREAD

**Issue by jazst21** [aws-samples/websocket-chat-application#5]
Error: src/app/services/websocket.service.ts:6:36 - error TS2307: Cannot find module '../../../../infrastructure/resources/models/websocket-auth-event' or its corresponding type declarations.

6 import { WebsocketAuthEvent } from '../../../../infrastructure/resources/models/websocket-auth-event';

**Comment by santatamas** [comment]
Thanks for reporting this! I'll have a look this week.

**Comment by santatamas** [comment]
Thanks for reporting this! I'll have a look this week :)

**Comment by santatamas** [comment]
Hi!

The issue was an unused file reference in the websocket service that had to be removed. I've pushed the changes, please have another look :) With that I've also updated the angular packages.

Kind Regards,
Tamas

**Comment by jazst21** [comment]
validated. thanks

**Comment by santatamas** [comment]
Great, thanks!
