### ISSUE TITLE
Need help regarding "Domain already associated with another user pool."

### ISSUE THREAD

**Issue by takeda-ma** [aws-samples/websocket-chat-application#56]
I got the following error after I tried "cdk deploy" everything looks fine until the frontend stack

```
11:39:20 PM | CREATE_FAILED        | AWS::Cognito::UserPoolDomain                    | UserPoolDomainD0EA232A
Domain already associated with another user pool. (Service: AWSCognitoIdentityProviderService; Status Code: 400; Error Code: InvalidParameterException; Request ID: c3d74165-6bdc-4442-884b-b3029be091
c5; Proxy: null)
```

Here is how I do the declaration of frontend stack. I am not sure what to put here so I just came up with random string.
![cd err2](https://github.com/aws-samples/websocket-chat-application/assets/84765421/b91f07d7-f5eb-47b4-b0db-b7ceb71177ba)

**Comment by takeda-ma** [comment]
turns out I already used this sample before and ran it again.

**Comment by santatamas** [comment]
Hi! Yeah if you try to run it in a different account but in the same region, it won't let you. Cognito domain names need to be unique in a given region.
